package com.mov.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.persistence.Id;

@Entity
@Table(name = "movies")
public class Movie {
	
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
//	  
	  
	@NotNull
	private String name;
	@NotNull
	private String genre;
//	@Getter
//	@Setter
//	private String releaseDate;
//	@Getter
//	@Setter
//	private String shortDescription;
	
//	public Movie(String name, String genre, String releaseDate, String shortDescription) {
//		this.name = name;
//		this.genre = genre;
//		this.releaseDate = releaseDate;
//		this.shortDescription = shortDescription;
//	}
	public Movie() { }
	
	public Movie(long id) {
		this.id = id;
	}
	
	public Movie(String name, String genre) {
		this.name = name;
		this.genre = genre;
	}
	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public void setGenre(String genre) {
		this.genre = genre;
	}
	
	public String getName() {
		return this.name;
	}
	
	public String getGenre() {
		return genre;
	}
}
