CREATE TABLE `movies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(50) DEFAULT NULL,
  `year` varchar(20) DEFAULT NULL,
  `rated` varchar(200) DEFAULT NULL,
  `released` varchar(200) DEFAULT NULL,
  `runtime` varchar(200) DEFAULT NULL,
  `genre` varchar(200) DEFAULT NULL,
  `director` varchar(200) DEFAULT NULL,
  `writer` varchar(500) DEFAULT NULL,
  `actors` varchar(100) DEFAULT NULL,
  `plot` varchar(500) DEFAULT NULL,
  `country` varchar(200) DEFAULT NULL,
  `awards` varchar(200) DEFAULT NULL,
  `poster` varchar(200) DEFAULT NULL,
  `metascore` varchar(20) DEFAULT NULL,
  `imdbRating` varchar(20) DEFAULT NULL,
  `imdbVotes` varchar(20) DEFAULT NULL,
  `imdbID` varchar(20) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `dvd` varchar(50) DEFAULT NULL,
  `boxOffice` varchar(50) DEFAULT NULL,
  `production` varchar(100) DEFAULT NULL,
  `website` varchar(200) DEFAULT NULL,
  `votes` varchar(255) DEFAULT NULL,
  `language` varchar(255) DEFAULT NULL,
  `discriminator` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8