CREATE TABLE imdbMovies(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	title varchar(20),
	year varchar(20),
	rated varchar(20),
	released varchar(20),
	runtime varchar(20),
	genre varchar(20),
	director varchar(20),
	writer varchar(20),
	actors varchar(20),
	plot varchar(20),
	language varchar(20),
	country varchar(20),
	awards varchar(20),
	poster varchar(20),
	metascore varchar(20),
	imdbRating varchar(20),
	imdbVotes varchar(20),
	imdbID varchar(20),
	type varchar(20),
	dvd varchar(20),
	boxOffice varchar(20),
	production varchar(20),
	website  varchar(20),
	response varchar(20)
);